name: Build on Ubuntu 22.04

on:
  push:
    branches:
      - gitactions
      - preworkingstate
      - working_w_cicd
  pull_request:
    branches:
      - gitactions
      - preworkingstate
      - working_w_cicd

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential make

    - name: Copy repository to parent directory
      run: |
        cmake --version 
        gcc --version
        cd $GITHUB_WORKSPACE/..
        cd aos-mbd
        git status
        git log --oneline
        ls
        pwd
        nvm use 22.2.4
        make
        make test-onnx

    - name: Post build clean up
      run: |
        rm -rf $GITHUB_WORKSPACE/..
